# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@1
  displayName: 'Archive files'
  inputs:
    includeRootFolder: false
    archiveType: zip
    enabled: false

- task: CopyFiles@2
  displayName: 'Copy Files to: \'
  inputs:
    SourceFolder: ITGlueAPI
    TargetFolder: '\'

- task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8
  displayName: 'Pester Test Runner'
  inputs:
    scriptFolder: '$(System.DefaultWorkingDirectory)\ITGlueAPI\Tests\'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
